apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-service
  template:
    metadata:
      labels:
        app: package-service
    spec:
      containers:
        - name: package-service
          image: hiresphere-package-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7500
          env:
            - name: PORT
              value: "7500"
            - name: CLIENT_ORIGIN
              value: "http://127.0.0.1:5173"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: "hirespheredb"
---
apiVersion: v1
kind: Service
metadata:
  name: package-service
spec:
  selector:
    app: package-service
  ports:
    - protocol: TCP
      port: 7500
      targetPort: 7500
  type: ClusterIP
