apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: hiresphere-evaluation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7600
          env:
            - name: PORT
              value: "7600"
            - name: CLIENT_ORIGIN
              value: "http://127.0.0.1:5173"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: "hirespheredb"
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
spec:
  selector:
    app: evaluation-service
  ports:
    - protocol: TCP
      port: 7600
      targetPort: 7600
  type: ClusterIP
