apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: hiresphere
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - port: 4005
      targetPort: 4005
