apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: hiresphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 164885464221.dkr.ecr.ap-south-1.amazonaws.com/hiresphere-evaluation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4005
          env:
            - name: PORT
              value: "4005"
            - name: CLIENT_ORIGIN
              value: http://a22a9b1f7363b4848980e865dab06576-543859913.ap-south-1.elb.amazonaws.com
          envFrom:
            - configMapRef:
                name: hiresphere-config
            - secretRef:
                name: hiresphere-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 4005
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4005
            initialDelaySeconds: 30
            periodSeconds: 20
