apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewer-service
  namespace: hiresphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interviewer-service
  template:
    metadata:
      labels:
        app: interviewer-service
    spec:
      containers:
        - name: interviewer-service
          image: 164885464221.dkr.ecr.ap-south-1.amazonaws.com/hiresphere-interviewer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"
            - name: CLIENT_ORIGIN
              value: http://frontend-service:3000
          envFrom:
            - configMapRef:
                name: hiresphere-config
            - secretRef:
                name: hiresphere-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 30
            periodSeconds: 20
