apiVersion: v1
kind: Service
metadata:
  name: live-session-service
  namespace: hiresphere
spec:
  type: ClusterIP
  selector:
    app: live-session-service
  ports:
    - port: 4007
      targetPort: 4007
