apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: hiresphere
spec:
  type: ClusterIP
  selector:
    app: submission-service
  ports:
    - port: 4004
      targetPort: 4004
