name: Deploy HireSphere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure Kubernetes
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name hiresphere-cluster

      - name: Build Frontend
        run: |
          docker build -t 164885464221.dkr.ecr.ap-south-1.amazonaws.com/hiresphere-frontend:latest ./frontend

      - name: Push Frontend
        run: |
          docker push 164885464221.dkr.ecr.ap-south-1.amazonaws.com/hiresphere-frontend:latest

      - name: Deploy Kubernetes
        run: |
          kubectl apply -f k8s/ --recursive --validate=false
          kubectl rollout restart deployment/frontend -n hiresphere
